// <auto-generated />
using System;
using ConexaoMySql.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ConexaoMySql.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.10");

            modelBuilder.Entity("ConexaoMySql.Models.Produto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("VARCHAR(20)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.ToTable("Produto");

                    b.HasData(
                        new
                        {
                            Id = new Guid("41afaa64-ad63-45bd-a336-e555e90ef217"),
                            Nome = "Caneta Bic",
                            Valor = 1m
                        },
                        new
                        {
                            Id = new Guid("cdac4b98-6c6e-4fcf-b849-b9a191eb5f2f"),
                            Nome = "Caneta Azul",
                            Valor = 1.39m
                        },
                        new
                        {
                            Id = new Guid("6bd213de-4805-4f39-9213-0eefb04631e4"),
                            Nome = "Caneta Vermelha",
                            Valor = 1.40m
                        },
                        new
                        {
                            Id = new Guid("52e8f5c6-be1f-455b-b7ca-be70fd1f82ca"),
                            Nome = "Caneta Preta",
                            Valor = 1.41m
                        },
                        new
                        {
                            Id = new Guid("c8a03f4d-4fad-4326-832c-7ecd24da321d"),
                            Nome = "Lápis",
                            Valor = 0.37m
                        },
                        new
                        {
                            Id = new Guid("34d0100c-ce64-44c2-bbd9-e1bde0ba8264"),
                            Nome = "Borracha",
                            Valor = 0.74m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
