// <auto-generated />
using System;
using ConexaoOracle.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

namespace ConexaoOracle.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210924201701_CriarTabela")]
    partial class CriarTabela
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ConexaoOracle.Models.Produto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("VARCHAR(20)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.HasKey("Id");

                    b.ToTable("Produto");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aee5b12c-c6bd-4c2e-92e7-32a1eff004d2"),
                            Nome = "Caneta Bic",
                            Valor = 1m
                        },
                        new
                        {
                            Id = new Guid("64329454-2845-4b5e-b3e1-bf97a663f08c"),
                            Nome = "Caneta Azul",
                            Valor = 1.39m
                        },
                        new
                        {
                            Id = new Guid("51189550-5e5a-4d09-8531-1aa32610e3f3"),
                            Nome = "Caneta Vermelha",
                            Valor = 1.40m
                        },
                        new
                        {
                            Id = new Guid("23fcf005-a96c-4ad8-881f-e6f3b2a46290"),
                            Nome = "Caneta Preta",
                            Valor = 1.41m
                        },
                        new
                        {
                            Id = new Guid("5e49dc28-26ff-4d5f-8da1-5cce451e79b6"),
                            Nome = "Lápis",
                            Valor = 0.37m
                        },
                        new
                        {
                            Id = new Guid("d166b9b4-54e3-4452-9799-d8f59ac76ce0"),
                            Nome = "Borracha",
                            Valor = 0.74m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
